---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: vcluster-quota-resources
spec:
  hard:
    requests.cpu: "3"
    requests.memory: 3Gi
    requests.storage: 2Gi
    requests.ephemeral-storage: 3Gi
    limits.cpu: "6"
    limits.memory: 6Gi
    limits.ephemeral-storage: 6Gi

---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: vcluster-quota-objects
spec:
  hard:
    pods: "15"
    services: "15"
    services.nodeports: "5"
    services.loadbalancers: "2"
    configmaps: "50"
    secrets: "50"
    persistentvolumeclaims: "5"

---
apiVersion: v1
kind: LimitRange
metadata:
  name: vcluster-limit-range
spec:
  limits:
  - default:
      memory: 512Mi
      cpu: "1"
    defaultRequest:
      memory: 128Mi
      cpu: 100m
    min:
      memory: 128Mi
      cpu: 10m
    max:
      memory: 2Gi
      cpu: "2"
    type: Container
